services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    pull_policy: never
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    pull_policy: never
  video-service:
    build:
      context: .
      dockerfile: video-service/Dockerfile
    pull_policy: never
  processing-service:
    build:
      context: .
      dockerfile: processing-service/Dockerfile
    pull_policy: never
  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    pull_policy: never