spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    events:
      exchange: video.processing.events.exchange
      routing-key:
        completed: video.processing.completed
        failed: video.processing.failed

    notification:
      queue: video.processing.notification-service.queue

server:
  port: 8084